# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Test

on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Bootstrap Packages
        run: npm run setup-full
      - name: Dependency Check
        if: ${{ matrix.node-version == '14.x' }}
        run: npm run test:depcheck
      - name: Lint / Typings / Unit / Smoke Test
        run: npx run-s test:typings
